# Generated by Django 2.0 on 2019-11-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractorname', models.CharField(max_length=100)),
                ('contractorid', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('mailid', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contractor',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=100)),
                ('staffid', models.CharField(max_length=100)),
                ('desgination', models.CharField(max_length=100)),
                ('mailid', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorname', models.CharField(max_length=100)),
                ('mailid', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'visitor',
            },
        ),
    ]
