# Generated by Django 2.0 on 2019-11-23 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('intime', models.TimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'entryexit',
            },
        ),
    ]
