# Generated by Django 2.0 on 2019-11-24 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_entryexit'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryexit',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
