# Generated by Django 2.0 on 2019-11-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_entryexit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='qrimage',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='visitor',
            name='qrimage',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
